### ISSUE TITLE
some bugs and suggestions

### ISSUE THREAD

**Issue by snoopein** [romgrk/termrk#5]
I love this package it's the best terminal for atom, beacause it looks like a real terminal and it can run programs like python console ...
When I try to use uppercase I have this error : "Uncaught TypeError: Cannot read property 'toLowerCase' of null" but it stil work.
I have some suggestions :
-Paste in the terminal.
-Exit a terminal (exit command dosen't work).
-Resize the terminal.

**Comment by fbob** [comment]
Indeed awesome package :+1:
May I add:
- show more than one terminal at a time (something like pane splits)
- move terminals around like other panes 

Anyway termrk is perhaps one of the best terminal emulator for atom.
Good job, thanks !

**Comment by romgrk** [comment]
- exit a terminal: `exit` command works, but the current behaviour is to restart a new process when the shell exits. I'll add a setting to control the behaviour. Otherwise, I'va added a `close-terminal` keybinding , `ctrl-escape`, which closes the current terminal.
- paste: added a command to handle that, as long as you have something mapped to `core:paste`, it should work fine. (usually it's `ctrl-v` or `shift-insert`)
- resize: workin' on it.

And for your issue, it's fixed but not published yet. I'll wait till then before closing.

**Comment by romgrk** [comment]
Resize is finalized. For the issue, I'll assume it's fixed, reopen if it happens again.
