### ISSUE TITLE
Focus on termrk:show command when it is visible but unfocused

### ISSUE THREAD

**Issue by olmokramer** [romgrk/termrk#67]
Nothing happens when the terminal panel is visible but not focused and I trigger the `termrk:show` command from a keybinding. It would be nice if the panel gained focus when the show command is triggered, then I can open/focus it with the same keybinding. But now I have to use the mouse to focus the terminal

**Comment by romgrk** [comment]
Yes, it might be very possible. 
I recall a previous issue being something like this but reversed, and I had to split the `show` and `focus` command. Although it surprises me. I will investigate into it.

**Comment by romgrk** [comment]
Reference: https://github.com/romgrk/termrk/issues/30
Associated commit: https://github.com/romgrk/termrk/commit/4896e4ec14ca7a76a5f4c6b9631091879ba95092

Yes, now I remember. The `show` command only shows the panel if not visible. Returns otherwise. 
As for your current issue, the `focus` command has the desired behavior => 
    _focus panel + show if hidden_

I would prefer not to modify the show command and leave it as is, because I think it makes more sense this way, and it keeps things simple:
`show` shows the panel
`focus` focuses the panel

I will close, but do not hesitate to comment further or reopen if you feel this should be adjusted otherwise.

**Comment by olmokramer** [comment]
Well in that case I would like to file a report that the focus command does not trigger when the package has not been activated yet... Adding it to the activationCommabds in your package.json should fix that :-)
