### ISSUE TITLE
Run a file in terminal

### ISSUE THREAD

**Issue by arrayoutofbounds** [romgrk/termrk#69]
I have a new language that I am working on for research and I want to be able to run that file ( with a certain command line path) in the terminal. How can I add that feature?

**Comment by romgrk** [comment]
I would say the best would be to use a custom user command:
https://github.com/romgrk/termrk#user-commands-experimental

Example: in `$ATOM_HOME/userCommands.cson`:

``` cson
'foobar':
  command: 'customCommand --option=value $FILE'
```

Wiil auto-generate the atom-command `termrk:command-foobar`. The file will have to be saved before running the command, as I don't recall including an auto-save option in there.
This feature is very basic but it should be enough, otherwise let me know I could add some options.

**Comment by romgrk** [comment]
Closing, considered as resolved.
