### ISSUE TITLE
X-selection-paste (middle-click paste) not working in termrk

### ISSUE THREAD

**Issue by real-milos** [romgrk/termrk#70]
...at least not for me.

**Comment by romgrk** [comment]
Perfectly normal, feature isn´t implemented. (Or at least, not by me — `term.js` might have it)

I must confess that being a _vim_ user I tend to avoid all possible contact with the mouse, and have therefore low interest in adding any feature that is mouse-related («you always develop the products you´d like to use»). Nonetheless I´ll check if I can bind some events and some listeners in there to trigger the `paste` command. Let me get back to you on this.

**Comment by real-milos** [comment]
Thanks for the quick answer and your willingness to implement something you won't use yourself. I am also a (neo)vim user myself, but if there's one thing that I think can be done faster with the cursor, it has to be copying and pasting random strings from the browser window through the selection buffer.

Since this is not implemented yet, consider this issue a feature request, not a bug report :)

**Comment by romgrk** [comment]
These days I really doesn't use Atom at all, because of Neovim & others; but I know I really hate the feeling when you get stuck in an inactive repo/upstream. So here you go ∴ 005453e8443c5eac28654b1cd9544bf7de957a03 (200th commit!)

I don´t know if you´re comfortable updating from that commit, but if you do it would be awesome because I haven´t tested anything, and I'd rather have some feedback before publishing.
(Oh, and also thanks: despite being on linux for years I had never quite understood what the hack was going on with the clipboard(s?). Now I do.)

**Comment by real-milos** [comment]
I just tested (sorry for taking so long), and it works just as expected. I'm usually the one to try and bend things 'til they break, but I've got no idea how to test this any further, it's that simple. My guess is you can go ahead and publish :)

Btw I really value the fact that you took the time and effort to implement this. I see from the diff it couldn't have been _too_ hard for you, but it was a completely selfless act on your part and that is not taken for granted. Thank you, and congrats on the 200th commit! Keep it up :+1:
